name: Build Node-RED ARMv7

on:
  schedule:
    - cron: '0 3 * * *'   # täglich um 03:00 UTC
  workflow_dispatch:      # manuell auslösbar

env:
  IMAGE_NAME: ipc-nodered
  TARGET_PLATFORM: linux/arm/v7

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Node-RED version
        run: |
          LATEST=$(curl -s https://registry.hub.docker.com/v2/repositories/nodered/node-red/tags | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+' | sort -Vr | head -n1)
          echo "NODERED_VERSION=$LATEST" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ env.TARGET_PLATFORM }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.NODERED_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            NODERED_VERSION=${{ env.NODERED_VERSION }}
