name: Build Node-RED ARMv7 with contrib nodes

on:
  schedule:
    - cron: '0 3 * * *'  # täglich um 03:00 UTC
  workflow_dispatch:

env:
  IMAGE_NAME: ipc-nodered
  TARGET_PLATFORM: linux/arm/v7

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check latest Node-RED version
        id: version-check
        run: |
          LATEST=$(curl -s "https://registry.hub.docker.com/v2/repositories/nodered/node-red/tags?page_size=100" \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+(\.[0-9]+)?$' \
            | sort -Vr | head -n1)

          echo "🔧 Latest Node-RED version: $LATEST"
          echo "NODERED_VERSION=$LATEST" >> $GITHUB_ENV

          if [ -f .nodered-version ]; then
            OLD=$(cat .nodered-version)
            if [ "$OLD" = "$LATEST" ]; then
              echo "✅ Version $LATEST already built – skipping"
              echo "skip=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi

          echo "skip=false" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.version-check.outputs.skip != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: steps.version-check.outputs.skip != 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for ARMv7
        if: steps.version-check.outputs.skip != 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.TARGET_PLATFORM }}
          push: true
          provenance: false
          build-args: |
            NODERED_VERSION=${{ env.NODERED_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.NODERED_VERSION }}
            ghcr.io/${{ github.repository }}:latest

      - name: Update .nodered-version and commit
        if: steps.version-check.outputs.skip != 'true'
        run: |
          echo "${NODERED_VERSION}" > .nodered-version
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .nodered-version
          git commit -m "Update Node-RED version to ${NODERED_VERSION}"
          git push
